# Generated by Django 4.1.2 on 2022-10-15 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_alter_employees_employee_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_requirements', models.TextField(verbose_name='Инструкция характеризуется следующими признаками')),
                ('topic', models.CharField(max_length=100, verbose_name='Тема')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('file_link', models.URLField(verbose_name='Ссылка на файл')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employees', verbose_name='Автор')),
            ],
        ),
    ]
